### ISSUE TITLE
Sagittarius: Failed to detect gc-threaded on FreeBSD

### ISSUE THREAD

**Issue by okuoku** [okuoku/yunibase#10]
``` cmake
//Path to a library.
BOEHM_GC_LIBRARIES:FILEPATH=/usr/local/lib/libgc.so
```

```
Performing C SOURCE FILE Test GC_GET_PARALLEL_WORKS failed with the following ou
tput:
Change Dir: /home/vagrant/yunibase/impl-stable/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/gmake" "cmTC_9f880/fast"
/usr/local/bin/gmake -f CMakeFiles/cmTC_9f880.dir/build.make CMakeFiles/cmTC_9f8
80.dir/build
gmake[1]: Entering directory '/home/vagrant/yunibase/impl-stable/build/CMakeFile
s/CMakeTmp'
Building C object CMakeFiles/cmTC_9f880.dir/src.c.o
/usr/bin/cc  -DGC_THREADS -I/usr/local/include  -fPIC -Wall  -DGC_GET_PARALLEL_W
ORKS -L   -o CMakeFiles/cmTC_9f880.dir/src.c.o   -c /home/vagrant/yunibase/impl-
stable/build/CMakeFiles/CMakeTmp/src.c
cc: error: no such file or directory: 'CMakeFiles/cmTC_9f880.dir/src.c.o'
CMakeFiles/cmTC_9f880.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_9f88
0.dir/src.c.o' failed
gmake[1]: *** [CMakeFiles/cmTC_9f880.dir/src.c.o] Error 1
gmake[1]: Leaving directory '/home/vagrant/yunibase/impl-stable/build/CMakeFiles
/CMakeTmp'
Makefile:126: recipe for target 'cmTC_9f880/fast' failed
gmake: *** [cmTC_9f880/fast] Error 2

Return value: 1
Source file was:
#include <gc.h>
int main() {
int i= GC_get_parallel();
return 0;
}
```

`FBSD11`

It seems CMake failed to generate temporary project for try-compile.

**Comment by okuoku** [comment]
https://bitbucket.org/ktakashi/sagittarius-scheme/commits/6916e290b1fedffa685c0c3247153e2ca0f5151f
https://github.com/spurious/sagittarius-scheme-mirror/commit/8973a933424270ad4edea7fbe52e64e500b2ef94

Upstream patch indicates the project having something wrong with header configuration. BSD libc indeed have `B38400` etc on `<sys/_termios.h>` -- so it would be worth to extract CMake checks and try them without other CMake checks.

**Comment by ktakashi** [comment]
The root cause of the compilation error was missing couple of variables. e.g. `NL0`. I've only checked PC BSD 10 (based on Free BSD 10) and not Free BSD 11. So this might not be the case on the latest version. 

I wasn't sure which project you are mentioning with _the project_ but I believe header configuration itself wouldn't be an issue since I'm using almost plain environment (unless VBox does something strange).

**Comment by okuoku** [comment]
For `NL0`, it is XSI (ie. XOPEN) interface -- POSIX(base) systems may not have ones. POSIX 2008 moved some of them into Base though.
(In POSIX-speak, these are "[symbolic constant](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_374)"s so you can check them with `#ifdef`s anyway.)

For header configuration, "expected C symbols are not defined" kinds of problems are sometimes caused with inconsistent [feature test macros](http://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html) usage. Since we have some sort of visibility problem, I suspected CMake injected some of these macro during TRY-COMPILE phase -- it turned out it is not the case, bah.

[As you mentioned](https://twitter.com/tk_riple/status/700779200140042240), enforcing `gc-thread` would be a solution. But I'm not sure any background why FreeBSD has separate packages for BoehmGC...

**Comment by okuoku** [comment]
Upstream `0.7.3` successfully detected `gc-thread`. CLOSE.
