### ISSUE TITLE
Sagittarius: Mysterious failure on zlib stub generation on FBSD 10/11

### ISSUE THREAD

**Issue by okuoku** [okuoku/yunibase#19]
Sagittarius current sometimes fail to build on FBSD.

It isn't reproducible every time and re-running build (by hand) fixes it mysteriously... Perhaps something wrong with build script for Vagrant.

On https://github.com/okuoku/yunibase/commit/5982ea42c2ab7980efb4d8a39a1559c5d7220388

```
Unhandled exception
  Condition components:
  1. &undefined
  2. &who equal?
  3. &message unbound variable equal? in library (sagittarius cgen cise)
  4. &stack-trace

stack trace:
  [1] rec
    src: (equal? file current-file)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/sagittarius/cgen/cise.scm":217
  [2] rec
    src: (equal? file current-file)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/sagittarius/cgen/cise.scm":217
  [3] failure
    src: (rec x)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/sagittarius/cgen/cise.scm":227
  [4] failure
    src: (rec x)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/sagittarius/cgen/cise.scm":227
  [5] call-with-output-string
    src: (proc port)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/sagittarius/io.scm":91
  [6] (#f proc)
  [7] (cgen-genstub lambda9072)
  [8] port-fold
    src: (fn item r)
    "/home/vagrant/yunibase/impl-current/sagittarius/sitelib/util/port.scm":77
  [9] #f
    src: (thunk)
    "/home/vagrant/yunibase/impl-current/sagittarius/lib/core/io.scm":57
  [10] dynamic-wind
  [11] dynamic-wind
  [12] main
    src: (proc (car l))
gmake[5]: *** [build/ext/zlib/CMakeFiles/sagittarius--zlib_genstub] Error 70
```

**Comment by ktakashi** [comment]
Haven't check the script, but one possibility I can think of is that using multiple process of make (say `make -j8`). Current library caching on Sagittarius isn't absolutely safe on multi process. So disabling it would fix (if you are using it, though).

**Comment by okuoku** [comment]
Yunibase(the build script) currently does not use any parallel build features on `gmake`. ... but it uses `gmake` for every build even on BSDs (for analytic purposes). It has some chance to introduce incompatibilities between CMake generated Makefiles e.g. pathname handling -- #10 did not show any difference in this regard though. 

Since I don't see any problem with physical machines, I think there is something wrong with clocking on the VM. (Yunibase uses FreeBSD official Vagrant images for VirtualBox)

**Comment by okuoku** [comment]
Needs revisit. Closing this right now anyway.
