### ISSUE TITLE
Sagittarius: Remove .sagittarius on stable->current boundary

### ISSUE THREAD

**Issue by okuoku** [okuoku/yunibase#31]
It seems build aborting sometimes creates corrupt bytecode cache.

```
Unhandled exception
  Condition components:
  1. &compile
    program: (import (rnrs) (getopt) (sagittarius document html))
    source: "/home/oku/local/repos/yunibase/impl-current/sagittarius/doc/gendoc":2
  2. &compile
    program: (library (sagittarius document html) (export scribble-file->
    source: "/home/oku/local/repos/yunibase/impl-current/sagittarius/sitelib/sagittarius/document/html.scm":34
  3. &undefined
  4. &who raise
  5. &message unbound variable raise in library (core)
  6. &stack-trace
```
1. set `SAGITTARIUS_CACHE_DIR` before build (stable/current)
2. Remove the cache directory for current one before build

**Comment by ktakashi** [comment]
Ah, this is (probably) because building HEAD used old caches (e.g. cache from previous commit). I've moved `raise` from `(core)` to `(core errors)` recently and got the same issue when I forgot to clear the cache.

It is a good idea to clear cache before building HEAD to avoid such a problem.

**Comment by okuoku** [comment]
We don't cache builds any longer. Close as WONTFIX.
