### ISSUE TITLE
Sagittarius: some test cause Out-of-memory on Cygwin64/Linux64

### ISSUE THREAD

**Issue by okuoku** [okuoku/yunibase#8]
```
%%%% Starting test HMAC tests
# of expected passes      7

out of memory (288). aborting...out of memory (32). aborting...
```

`0.7.0`.

**Comment by ktakashi** [comment]
Currently executing tests requires approx 2GB memory... Using `peflags` may help for quick workaround.

**Comment by okuoku** [comment]
Thanks for the advice, 
applying `peflags` has certain pros/cons(on reproducibility) but I think it is far more better than just leaving tests `SKIP_TEST`...

Since every Cygwin64 binary should be `--bigaddr`, I think we already have 4GiB of address space.

Uh, anyway, it's time to plug more memory to the build node..

**Comment by okuoku** [comment]
```
%%%% Starting test process tests
FAIL call (1)
        expected value: #f
          actual value: #<condition
 #<system-error 12>
 #<&message command: `/yunisrc/yunibase/impl-current/sagittarius/build/test-proc.bin (process)`.
message fork failed. Cannot allocate memory>
 #<stack-trace cause=#f>
>
```

`production` `Linux`

Currently 1/3, not reproducible.

**Comment by okuoku** [comment]
(reopen)

**Comment by okuoku** [comment]
Keep this unresolved. Yunibase now ignore every test failure. 
https://github.com/okuoku/yunibase/issues/12
I don't think I have time to chase every single test failure for each 9 (plus Gambit and Psyntax-mosh) implementations..
